import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/Provider";
import { ThemeProvider } from "next-themes";
import ToastProvider from "@/components/toastProvider/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "N&N Finance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={inter.className}>
          <ThemeProvider
            attribute="data-theme"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ToastProvider>
              <Providers>{children}</Providers>
            </ToastProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
